Dockerfile: upgrade to buster
On stretch there were some version problems:

...
  File "/usr/local/lib/python3.5/dist-packages/pdudaemon-0.1-py3.5.egg/pdudaemon/drivers/snmp.py", line 21, in <module>
  File "/root/.local/lib/python3.5/site-packages/pysnmp/hlapi/__init__.py", line 7, in <module>
    from pysnmp.proto.rfc1902 import *
  File "/root/.local/lib/python3.5/site-packages/pysnmp/proto/rfc1902.py", line 9, in <module>
    from pysnmp.proto import rfc1155, error
  File "/root/.local/lib/python3.5/site-packages/pysnmp/proto/rfc1155.py", line 50, in <module>
    class NetworkAddress(univ.Choice):
  File "/root/.local/lib/python3.5/site-packages/pysnmp/proto/rfc1155.py", line 55, in NetworkAddress
    def clone(self, value=univ.noValue, **kwargs):
AttributeError: module 'pyasn1.type.univ' has no attribute 'noValue'
2019-03-05 02:13:14,182 INFO exited: pdudaemon (exit status 1; not expected)
2019-03-05 02:13:15,183 INFO gave up: pdudaemon entered FATAL state, too many start retries too quickly

Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>